### ISSUE TITLE
Have bootloader at end of memory

### ISSUE THREAD

**Issue by AlessandroAU** [ferenc-nemeth/stm32-bootloader#1]
If I wanted to have the bootloader at the end of the flash as opposed to at the start, how would I need to configure the VECT_TAB_OFFSET and FLASH (rx) parameters?

**Comment by ferenc-nemeth** [comment]
Execution starts from the beginning, therefor you need a small code at the beginning that jumps to your bootloader's new location. I wouldn't recommend that though, it just makes your software more complicated for no real benefit.
