### ISSUE TITLE
how to use the xmodem128 boot on stm32f072rbc chip?

### ISSUE THREAD

**Issue by zouzhe1** [ferenc-nemeth/stm32-bootloader#3]
can you help me to check my code problem?

use you code changed.but it not run normal.
when i send xmodem by secureCRT,it  stop...

**Comment by ferenc-nemeth** [comment]
Xmodem should work on any hardware. The low lever flash writing functions the ones you need to rewrite.
Check your microcontroller's datasheet and the related HAL features.
